AWSTemplateFormatVersion: 2010-09-09
Description: Lab 1.1.4 CFN Template to Create S3 Bucket

Parameters:
  BucketName:
    Description: "The name of the bucket"
    Type: "String"
    Default: "jw-not-valid-bucket-name"
  OwnerName:
    Description: "Owner of the bucket"
    Type: String
    Default: "SRE"

Conditions:
  PreferredRegion: !Equals 
    - !Ref AWS::Region
    - us-east-2

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        !If
          - PreferredRegion
          - !Join
            - '-'
            - - !Ref AWS::AccountId
              - !Ref BucketName
          - !Join
            - '-'
            - - !Ref AWS::Region
              - !Ref BucketName
      Tags:
        - 
          Key: "Owner"
          Value: !Ref OwnerName

Outputs:
  S3Bucket:
    Description: S3 bucket has been created
    Value: !Ref S3Bucket
