---
AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation Template for s3 bucket
Resources:
  S3Bucket:
    DeletionPolicy: Delete
    Type: 'AWS::S3::Bucket'
    Description: Creating Amazon S3 bucket from CloudFormation
    Properties:
      # Dynamic Substitution Working
      # BucketName: !Sub ${AWS::AccountId}-${BucketName}
      #
      # Regional Logic Working (names have to be lower case)
      BucketName: !If [CreateBucketName, accountidbucketname, regionbucketname]
      #
      # Dynamic Substitution within Regional Logic NOT working
      # BucketName: !If [CreateBucketName, !Sub ${AWS::AccountId}-${BucketName}, !Sub ${AWS::Region}-${BucketName}]
  JoelsMyIamUser:
    Type: AWS::IAM::User
    Properties:
      UserName: JoelsReadOnlyUser
      Policies:
        - PolicyName: JoelsReadOnlyPolicy
          PolicyDocument:
            {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Sid": "MyReadOnlyBucketPolicyV1",
                        "Effect": "Allow",
                        "Action": [
                "s3:ListBucket",
                            "s3:GetObject*"
                        ],
                        "Resource": [
                            "arn:aws:s3:::s3-bucket-ro",
                            "arn:aws:s3:::s3-bucket-ro/*"
                        ]
                    }
                ]
            }

  UserPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy That Manages The User
      ManagedPolicyName: JoelsReadOnlyPolicyInsideMangedPolicy
      PolicyDocument:
        {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Sid": "MyReadOnlyBucketPolicyV1",
                    "Effect": "Allow",
                    "Action": [
            "s3:ListBucket",
                        "s3:GetObject*"
                    ],
                    "Resource": [
                        "arn:aws:s3:::s3-bucket-ro",
                        "arn:aws:s3:::s3-bucket-ro/*"
                    ]
                }
            ]
        }
      Users:
        - JoelsReadOnlyUser
Conditions:
  CreateBucketName: !Equals
    - !Ref "AWS::Region"
    - us-east-1
Parameters:
  BucketName:
    Type: String
  EnvType:
    Description: Environment type.
    Default: test
    Type: String
    AllowedValues:
      - prod
      - test
    ConstraintDescription: must specify prod or test.
Outputs:
  S3Bucket:
    Description: Bucket Template Creation.
    Value: !Ref S3Bucket
  MyStacksRegion:
    Value: !Ref "AWS::Region"
  AccountId:
    Value: !Ref "AWS::AccountId"
  # MyStacksUser:
  #   Value: !Ref "arn:aws:iam::*"
  # MyStacksPolicy:
  #   Value: !Ref "AWS::IAM::ManagedPolicy"
  IAMManagedS3AccessArn:
    Value: "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
    Export:
      Name: !Sub "${AWS::StackName}-s3-arn"
