---
AWSTemplateFormatVersion: "2010-09-09" 
Description: CloudFormation Template for s3 bucket
Resources:
  S3Bucket:
    DeletionPolicy: Retain
    Type: 'AWS::S3::Bucket'
    Description: Creating Amazon S3 bucket from CloudFormation
    Properties:
      BucketName: blueberrybucket1
Outputs:
  S3Bucket:
    Description: Bucket Template Creation.
    Value: !Ref S3Bucket
