---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  The most minimal S3 stack possible

Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: PublicReadWrite
      BucketName: jh-bucket