AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for s3 bucket 

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: stelligent-u-fidelisogunsanmi
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: S3Rule
            Status: Enabled 
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90 
                StorageClass: GLACIER
            NoncurrentVersionExpiration:
              NewerNoncurrentVersions: 5
              NoncurrentDays: 7
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1

      Tags:
        - Key: Environment 
          Value: Lab
Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: Name of the sample Amazon S3 bucket with a lifecycle configuration.