apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: custom-deployment
  name: custom-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: custom-deployment
  type: LoadBalancer
status:
  loadBalancer: {}
