---
version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install cfn-lint

  build:
    commands:
      - echo "Validating CFN Template"
      - cfn-lint 12-codepipeline/bucket.yaml
    finally:
      - echo "Template Validation Completed"

  post_build:
    on-failure: ABORT
