AWSTemplateFormatVersion: 2010-09-09
Description: Template used during the IAM  module for Jory to go through Stelligent U

Resources:
  IAMPolicy:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::324320755747:user/jory.garrido.labs
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: jory-stelliu-role
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'iam:GetAccountSummary'
                Resource: '*'
