apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: <cluster name>
  region: <aws region>
  # availabilityZones: ["us-east-1a", "us-east-1b"]

managedNodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 2
  - name: ng-2
    instanceType: t3.small
    desiredCapacity: 2
